### ISSUE TITLE
  Wire.reset();

### ISSUE THREAD

**Issue by amirjak** [cspwcspw/ESP32_CamToLCD#2]
In file included from C:\Users\amir\AppData\Local\Temp\arduino_modified_sketch_876811\CamToLCD.ino:24:0:

sketch\CAM_OV7670.h: In constructor 'pw_OV7670::pw_OV7670(int, int, int, int, int, int, const int*, void (*)(DMABuffer*), void (*)())':

CAM_OV7670.h:292:12: error: 'class TwoWire' has no member named 'reset'

       Wire.reset();           // Without this, we cannot always get XCLK clock going.

            ^

sketch\CAM_OV7670.h: In member function 'void pw_OV7670::TestSuite(char*)':

CAM_OV7670.h:372:12: error: 'class TwoWire' has no member named 'reset'

       Wire.reset();

            ^

exit status 1
'class TwoWire' has no member named 'reset'

**Comment by cspwcspw** [comment]
Yeah, looks like it has been removed from the new version of Wire library
because that functionality gets taken of elsewhere.

So perhaps just comment it out and see if indeed it is now redundant with
the later version of the Wire library.

https://github.com/espressif/arduino-esp32/issues/1679

Peter

**Comment by amirjak** [comment]
Thanks😁

**Comment by amirjak** [comment]
Awesome project😁

**Comment by amirjak** [comment]
Awesome project
